//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTML_UMA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Color_statusProduct
    {
        public int ID { get; set; }
        public Nullable<int> Color_ID { get; set; }
        public Nullable<int> Pro_ID { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual Color Color { get; set; }
    }
}
