//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTML_UMA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public int contact_ID { get; set; }
        public string contact_LastName { get; set; }
        public string contact_Name { get; set; }
        public string contact_Address { get; set; }
        public string contact_Phone { get; set; }
        public string contact_Email { get; set; }
        public string contactt_Content { get; set; }
    }
}
