//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTML_UMA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Information_Company
    {
        public int infor_ID { get; set; }
        public string infor_Namecompany { get; set; }
        public string infor_Address { get; set; }
        public string infor_Email { get; set; }
        public string infor_Hotline { get; set; }
        public string infor_Fax { get; set; }
        public string infor_Description { get; set; }
        public string Infor_maps { get; set; }
    }
}
