//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTML_UMA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Other_Address
    {
        public int user_ID { get; set; }
        public string other_Name { get; set; }
        public string other_Adress { get; set; }
        public string other_Email { get; set; }
        public string note { get; set; }
    }
}
