//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTML_UMA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Favourites = new HashSet<Favourite>();
            this.History_Product = new HashSet<History_Product>();
            this.LinkImages = new HashSet<LinkImage>();
            this.Orders = new HashSet<Order>();
        }
    
        public int pro_ID { get; set; }
        public string pro_code { get; set; }
        public Nullable<int> Menu_ID { get; set; }
        public Nullable<int> group_ID { get; set; }
        public string pro_Name { get; set; }
        public Nullable<decimal> pro_price { get; set; }
        public Nullable<int> pro_Quanty { get; set; }
        public string pro_Description { get; set; }
        public Nullable<int> pro_View { get; set; }
        public string pro_Image { get; set; }
        public Nullable<System.DateTime> pro_Date { get; set; }
        public string pro_Materials { get; set; }
        public Nullable<int> Color_ID { get; set; }
        public string pro_Size { get; set; }
        public string pro_Designer { get; set; }
        public string pro_Source { get; set; }
        public string pro_Instruction { get; set; }
        public Nullable<bool> pro_Status { get; set; }
        public string note { get; set; }
        public Nullable<bool> removeproduct { get; set; }
        public Nullable<int> OptionID { get; set; }
        public Nullable<bool> sale { get; set; }
        public Nullable<bool> fastProduct { get; set; }
        public Nullable<bool> newProduct { get; set; }
    
        public virtual Color Color { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Favourite> Favourites { get; set; }
        public virtual GroupProduct GroupProduct { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<History_Product> History_Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LinkImage> LinkImages { get; set; }
        public virtual Menu Menu { get; set; }
        public virtual OptionSale OptionSale { get; set; }
        public virtual OptionSale OptionSale1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}
