//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTML_UMA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slider
    {
        public int slide_ID { get; set; }
        public string slide_Image { get; set; }
        public string slide_Title { get; set; }
        public string slide_Description { get; set; }
        public string slide_Note { get; set; }
    }
}
